# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainDesign.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(448, 390)
        self.gridLayout_2 = QtWidgets.QGridLayout(Form)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.xInput = QtWidgets.QLineEdit(Form)
        self.xInput.setObjectName("xInput")
        self.gridLayout_2.addWidget(self.xInput, 3, 1, 1, 1)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.mapOut = QtWidgets.QLabel(Form)
        self.mapOut.setObjectName("mapOut")
        self.gridLayout.addWidget(self.mapOut, 0, 0, 1, 1)
        self.gridLayout_2.addLayout(self.gridLayout, 0, 0, 1, 3)
        self.outButton = QtWidgets.QPushButton(Form)
        self.outButton.setObjectName("outButton")
        self.gridLayout_2.addWidget(self.outButton, 4, 0, 1, 3)
        self.scaleInput = QtWidgets.QLineEdit(Form)
        self.scaleInput.setObjectName("scaleInput")
        self.gridLayout_2.addWidget(self.scaleInput, 3, 0, 1, 1)
        self.yInput = QtWidgets.QLineEdit(Form)
        self.yInput.setObjectName("yInput")
        self.gridLayout_2.addWidget(self.yInput, 3, 2, 1, 1)
        self.label = QtWidgets.QLabel(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setObjectName("label")
        self.gridLayout_2.addWidget(self.label, 2, 0, 1, 1)
        self.label_3 = QtWidgets.QLabel(Form)
        self.label_3.setObjectName("label_3")
        self.gridLayout_2.addWidget(self.label_3, 2, 2, 1, 1)
        self.label_2 = QtWidgets.QLabel(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        self.label_2.setObjectName("label_2")
        self.gridLayout_2.addWidget(self.label_2, 2, 1, 1, 2)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Карта"))
        self.mapOut.setText(_translate("Form", "TextLabel"))
        self.outButton.setText(_translate("Form", "Output"))
        self.label.setText(_translate("Form", "Масштаб:"))
        self.label_3.setText(_translate("Form", "Y:"))
        self.label_2.setText(_translate("Form", "X:"))
